language: java

branches:
  only:
    - master
    - develop

jdk:
  - oraclejdk8
#  - openjdk8
#  - oraclejdk7
#  - openjdk7
#  - openjdk6

after_success:
  - mvn clean cobertura:cobertura coveralls:report

  notifications:
      slack: rapidpm:giph6gm6CAPsatCNt5jHhnzN